# Generated by Django 2.1 on 2019-08-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20190804_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='classroom',
            field=models.CharField(default='Por asignar', max_length=200, verbose_name='Aula'),
        ),
    ]
