# Generated by Django 2.1 on 2019-08-04 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0006_auto_20190804_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='classroom',
            field=models.CharField(max_length=200, verbose_name='Aula'),
        ),
        migrations.AlterField(
            model_name='post',
            name='place',
            field=models.CharField(max_length=200, verbose_name='Edificio'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='teacher',
        ),
        migrations.AddField(
            model_name='post',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Profesor'),
        ),
    ]
