# Generated by Django 2.1 on 2019-08-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20190809_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='finalGrade',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=1, verbose_name='Promedio Final'),
        ),
    ]
