# Generated by Django 2.1 on 2019-08-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20190809_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='finalGrade',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Promedio Final'),
        ),
    ]
