# Generated by Django 2.1 on 2019-08-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20190804_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='place',
            field=models.CharField(max_length=200, null=True, verbose_name='Edificio'),
        ),
    ]
