# Generated by Django 2.1 on 2019-08-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_post_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='place',
            field=models.CharField(default='Por asignar', max_length=200, verbose_name='Edificio'),
        ),
    ]
