# Generated by Django 2.1 on 2019-08-05 03:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20190804_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='fstGrade',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Parcial 1'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='fthGrade',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Parcial 4'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='sndGrade',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Parcial 2'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='trdGrade',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Parcial 3'),
        ),
    ]
