# Generated by Django 2.1 on 2019-08-04 02:26

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pages.models.custom_upload_to, verbose_name='Imagen'),
        ),
    ]
